exec-once = ln -s /run/user/1000/hypr /tmp/hypr
exec-once = waybar
exec-once = ffplay -v 0 -nodisp -autoexit /usr/share/hyprland/startup.mp3
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = nm-applet
exec-once = flatpak run dev.deedles.Trayscale --hide-window
exec-once = flatpak run com.nextcloud.desktopclient.nextcloud
exec-once = hyprpaper
exec-once = ~/.config/hypr/Scripts/apod.sh
exec-once = ~/.config/hypr/Scripts/docked.sh
